### PR TITLE
Removes Portal dependency for RN0.26+

### PR DESCRIPTION
**Pull request by rajkissu**
This solves the issues raised in #12, as Portal has been removed from RN0.26

### CODE REVIEW

**Comment by duketwo** [comment]
Problem is when Statusbar == hidden, it will show up while the modal is open. But I assume this is rather a react-native bug.

**Comment by jeveloper** [comment]
Can you push this please
thanks

**Comment by jeveloper** [comment]
come on

**Comment by jeveloper** [comment]
wake up @niftylettuce

**Comment by niftylettuce** [comment]
Ah thank you!  Sorry merging now

**Comment by niftylettuce** [comment]
Released to NPM in v0.1.1

**Comment by jeveloper** [comment]
thank you !

**Pull request merged**
